### ISSUE TITLE
Simplify the Popcorn Maker canvas

### ISSUE THREAD

**Issue by benrito** [mozilla/popcorn-editor#72]
Make the default color of the canvas black; remove ability to change background color

**Comment by benrito** [comment]
@antiboredom

**Comment by benrito** [comment]
The canvas is now black in Sam's branch, and we don't need to worry about number 2.

Sam, can you merge this stuff into master?

**Comment by benrito** [comment]
@antiboredom see above

**Comment by secretrobotron** [comment]
The only thing dangling in this bug is the background colour, correct?

**Comment by secretrobotron** [comment]
I foresee a merge conflict.

**Comment by benrito** [comment]
Correct; but I don't think Sam committed anything to master.
