### ISSUE TITLE
Enable use of TV News Archive clips

### ISSUE THREAD

**Issue by benrito** [mozilla/popcorn-editor#80]
We want to enable people to search for clips on the TV News Archive and paste them into the media box, so they can be used in Popcorn sequences.

For each TV clip, there is already a Popcorn button in the share UI that is no longer functional. We could use that to get a link. But, it's pretty buried. Could we remove the number of clicks to get to this?

Even better:

Could we add a iframe modal view within Popcorn that allows people to search using the regular TV News Archive UI, but adds a button that can be clicked to add the clip? Would be an cross-iframe post message of some simple JSON.

**Comment by benrito** [comment]
@traceypooh per our earlier discussion; our deadline to get this in and ready for testing on spintime.tv is September 5th. What do you think? cc @antiboredom

**Comment by traceypooh** [comment]
actually!  i already updated archive.org site, for when an item has the "add to popcorn maker" type image/button/link is hit -- to go to the new editor and pre-load that asset!
(FYI / FWIW...)

re: clicks -- it was designed this way by an architect-level designer -- JSYK.  it wasn't an afterthought but specifically thought of this way.. 8-)

**Comment by benrito** [comment]
Aha! That's very useful. Will have to play around with it now.

What would be the best way to enable someone to add the clip to an existing project? Is there a copy-pastable link we can grab from the share flow and teach Popcorn how to parse it?

**Comment by benrito** [comment]
@traceypooh with the excellent URL parsing and the "add to popcorn" button, think we can close this, but... just thinking.

It would be cool to invoke clips from within the editor. Should we experiment with some kind of modal view that opens with a button?

You'd get the normal internet archive search interface in an iframe, but with one bit of heightened self-awareness. When loaded in an iframe, the archive search interface would have a button on each segment that would say "add to sequence."

Clicking the button would 

1) create a new track event that loads up the clip in the current sequence
2) closes the modal

What do you think?

**Comment by benrito** [comment]
Closing for now.
