### ISSUE TITLE
Limit the amount of tracks?

### ISSUE THREAD

**Issue by benrito** [mozilla/popcorn-editor#82]
For #79 and general usability, should we limit the number of tracks to some arbitrary number?  There's currently no limit. @antiboredom @secretrobotron

**Comment by secretrobotron** [comment]
@benrito we definitely can. Is there a reason to limit atm though? Is there an automatic process that makes a lot of tracks or something? If not, I'd suggest leaving it as arbitrary.

**Comment by benrito** [comment]
Not essential, I just observe a lot of confusion. 3-4 tracks are typically visible.

In addition to UI confusion, the fear is that someone creates 20 - 50 overlapping tracks and crashes the render pipeline...

**Comment by secretrobotron** [comment]
That's a super valid concern. Let's stick to 4.
