### ISSUE TITLE
Image edit pane

### ISSUE THREAD

**Issue by benrito** [mozilla/popcorn-editor#87]
Only:

Start, end and URL fields

Hide everything else

**Comment by secretrobotron** [comment]
You want to hide all of the Flickr functionality and stuff? Even `Link URL`? No prob to do, just lopping off a lot of functionality.

**Comment by benrito** [comment]
Yeah; none of those things are compatible with the render pipeline which ultimately gives you a flat .mp4.

**Comment by secretrobotron** [comment]
Ahhhhhh, of course!

🐗 destroying

**Comment by secretrobotron** [comment]
Is there a label that means the opposite of "enhancement"? 😜
