### ISSUE TITLE
Video resizing different between YouTube (iframe) and Archive (video)

### ISSUE THREAD

**Issue by benrito** [mozilla/popcorn-editor#92]
Videos from the archive use `<video>` tags, but videos from YouTube are `<iframe>`s or flash. When resizing, aspect ratios are conserved the same way (I think), but background colors are different. Archive videos have a transparent background, and YouTube ones are black.

**Comment by benrito** [comment]
preferred solution: limit the bounding box to the aspect ratio of the video, so the bounding box never exceeds the video

**Comment by secretrobotron** [comment]
@benrito can you link to a `<video>` you commonly use so I can test?

**Comment by benrito** [comment]
here’s an arbitrary TV archive URL that will queue a representative .mp4

https://archive.org/details/WTXF_20160919_090000_Fox_Morning_News_at_5A#start/2343.9/end/2373.9

**Comment by secretrobotron** [comment]
Let's try this approach. Relying on `jquery-ui` to give us good results.
