### ISSUE TITLE
Image plugin: use Internet Archive logo as default image

### ISSUE THREAD

**Issue by benrito** [mozilla/popcorn-editor#96]
Can we use an internet archive logo for the default image?

Expanded from #64 per @secretrobotron request

**Comment by secretrobotron** [comment]
@traceypooh is there a particularly great (vector?) logo we can use?

**Comment by secretrobotron** [comment]
How about ![https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Internet_Archive_logo_and_wordmark.svg/1054px-Internet_Archive_logo_and_wordmark.svg.png](https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Internet_Archive_logo_and_wordmark.svg/1054px-Internet_Archive_logo_and_wordmark.svg.png)
